name: CI-CD

on:
  push:
    branches:
    - main

jobs:
  my_ci_part:
    runs-on: macos-12
#Первым делом клонируем гит
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v3
    # - uses: actions/setup-node@v3
#Собираем проект
    - name: Build project
      run: ls -la
    - name: Build project1    
      run: npm install